workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: 16.0
      cocoapods: default
      groups:
        - app_store_credentials  # Add your Apple Developer credentials here
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd mobile
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd mobile/ios
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          cd mobile
          flutter build ipa --release \
            --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

